- css/index.css
- index.html
- js/index.js
- rest-time, real-time page가 분할 되어 있지 않았습니다.
- radio-box클릭 시 rest-time 버전으로 변경함.
- rest-time시에는 캐릭터가 멈춘 채로 타임바의 가운데에 위치시킴.
- rest-time시에 타임바는 그라데이션으로 모두 칠함.
캐릭터의 위치를 현재까지 일한 시간만큼 재배치할 코드부분입니다.
#51 이슈와 함께 완료해주시면 됩니다~~
> :sparkles: [feat] #54 Rest-time, Real-time page 분할

- diary.html
- index.html
- js/diary.js
- js/index.js
- 하루에는 하나의 일기만 작성이 가능합니다.
- 하지만 일일 일기 작성을 완료한 후에 nav bar의 Diary를 클릭하면 새로 작성할 수 있는, 중복 작성이 가능한 오류가 발생하였습니다.
- nav bar의 Diary를 클릭했을 때의 상태를 일일 일기 작성 전, 후로 나누었습니다.
- 전: 새로운 글을 작성할 수 있습니다.
- 후: 오늘 작성한 일기의 data를 불러옵니다. 
- 추가 리팩토링 사항은 일기 data를 불러올 때 self check list의 값, 즐겨찾기 여부까지 가져와야 합니다. (#58)
> #52 ♻️ [refactor] 일일 일기 중복 작성이 되지 않도록 구현

- css/diary.css
> :recycle: [refactor] send 버튼 border 없애기

- js/diary.js
- diaries 테이블의 state값이 true(1)일 경우 동일한 id의 companies의 total_good_state_count값 1증가 구현
- #66
> ♻️ [refactor] state의 값에 따라 companies 좋은 워라밸지표수 증가

- diary.html
- js/diary.js
- js/list.js
- self-check-result radio checked위치 조정 필요
- #58 
- #76 
- #78
> ✨ [feat] diary를 볼 때 question, star, answer 불러오기 성공

- js/diary.js
> :sparkles: [feat] diary 클릭시 모든 데이터 불러와 출력함

- js/diary.js
> :recycle: [refactor] 오늘의 일기 작성 후에 nav>diary 클릭시 오늘 작성한 글 불러오기 완성함

- js/diary.js
> :bug: [refactor] 첫 글을 작성할 때 username, question값 받아오기 수정 완료

- js/index.js
요소들을 id로 가져오는 코드가 겹쳐서 하나로 통일시켰습니다!
> [fix] 머지 후 에러 수정

- js/index.js
> [refactor] 일하는 시간이 아닐 때(근무 시간을 지났을 때), UI 완성 #51

- js/list.js
> :bug: [refactor] 한 자릿수의 날일 경우 앞의 0을 제거하여 출력

- js/list.js
if문 대신 Number를 통해 앞의 0 제거
- #94
> :recycle: [refactor] 한 자릿수의 날일 경우 Number로 앞의 0을 제거하여 출력

- js/diary-reading.js
- js/diary.js
- js/list.js
- 날짜에 기반한 question id가 불러와지지 않는 오류가 발생하였습니다. 
- 두자리수일 경우 17의 quesId를 받지만 한 자리수일 경우 3r와 같은 quesId를 받았던 것이 원인이었습니다.
- 따라서 정규표현식을 사용해 day의 두 번째 자리수가 숫자가 아닐 경우 제거하였습니다. 
- #97
> 🐛 [refactor] 날짜로부터 quesId 도출 성공

- js/mypage.js
- url: diaries/list/${user_id} -> diaries/${user_id}
> :bug: [refactor] mypage에서 사용자가 작성하나 diary 개수 get 완성

- join.html
- js/diary.js
- js/mypage.js
- diary 작성할 때: 모든 값 수정 가능, 커서 보임
- diary 볼 때: 모든 값 수정 불가능, 커서 안 보임
- #85
> :recycle: [refactor] diary를 보기만 할 때는 값 수정 락 걸기

- js/mypage.js
- 전: new Date로 변환하여 전달
- 후: innerHTML로 값을 그대로 string으로 가져와 전달
- #93
> 🐛 [refactor] payday값을 string으로 전달

- css/diary.css
- diary.html
- js/diary.js
nav bar에서 diary클릭시 diary post api가 작동이 되지 않는 오류가 발생했습니다. 
createDiary()에서 필요한 quesId가 NaN의 값을 지니고 있어 발생한 문제였습니다. 
오늘 날짜(today)를 String()으로 변환 후 substring()으로 일자만 발췌하여 Number로 변환하여 quesId를 할당하여 해결하였습니다. 
- #106
> :bug: [refactor] diary post api 500 error 해결

- js/list.js
- toLowerCase()로 제목을 소문자로 변경
- replaceAll(" ", "")로 제목의 공백 제거 
- #111
> :bug: [refactor] diary 검색 공백, 대소문자 상관없이 검색 구현

- join.html
- js/join.js
- :bug: [bug] #115 Others를 누른 뒤 저장이 안 됨
- #113
> :recycle: [refactor] 회사 GET API 연동 성공

- join.html
- js/join.js
- join post error 발생
- 회사 list를 get api로 가져온 뒤 맨 마지막에 Others 삽입
- 회사, payday를 각각 클릭시 해당 드롭다운이 접히고 클릭한 값이 해당 드롭다운에 나타남
- 회원가입이 성공하기 전에는 회사가 저장되지 않음
- #115
> :bug: [refactor] 회원가입 페이지의 회사 Others 저장 및 드롭다운 구현

- js/join.js
- Others를 선택할 경우 companyId는 companyLength+1
- Others를 선택했을 경우 #otherInput의 val()가 공백이 아닐 때만 join
- #119
> :bug: [refactor] Others 회사 저장됨

- css/list.css
- list.html
> 💄 [design] 날짜 버튼 삭제

- diary.html
- join.html
- js/join.js
- js/mypage.js
- list.html
mypage의 회원정보 수정에서 변경할 회사를 클릭했을 때 해당 회사가 회사 드롭다운에 잘 나타남
- #123
> :bug: [refactor] mypage의 회사 변경 오류 해결
